name: personaplex-overfit-hf
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - pip:
      - bitsandbytes>=0.43
      - aiohttp>=3.10.5,<3.11
      - einops==0.7
      - huggingface-hub[cli]>=0.24,<0.25
      - numpy>=1.26,<2.2
      - PyYAML>=6
      - protobuf>=3.19.6,<5
      - safetensors>=0.4
      - sentencepiece==0.2
      - sphn>=0.1.4,<0.2
      - tensorboard>=2.17,<2.19
      - sounddevice==0.5
      - pyloudnorm>=0.1.1
      - tqdm>=4.66
